pipeline {
	agent none
	stages {
	  stage('Run Tests') {
            parallel {
                stage('Test On Windows') {
                    steps {
                        sh "echo 'Hello'"
                    }
                }
                stage('Test On Linux') {
                    steps {
                        sh "echo 'Hello'"
                    }
                }
            }
        }
    }
}
